- name: play level variable 
  hosts: local 
  connection: local
  vars:
    COURCE: TYPING 
    DURATION: "30MINS daily"
    TAINER: "WEBSITE"
  tasks:
    - name: print variables
      vars: 
        COURCE: "MARKETING"
      ansible.builtin.debug:
       msg: "Course is {{ COURCE }}, Trainer is: {{ TAINER }}" 
