- name: file variable 
  hosts: local 
  connection: local

  vars_files:
  - course.yaml

  tasks:
    - name: print variables
      vars: 
    
      ansible.builtin.debug:
       msg: "Course is {{ COURCE }}, Trainer is: {{ TAINER }}" 
