- name: Print User name and password
  hosts: local
  connection: local
  vars_prompt:
  - name: "username"
    prompt: "enter your user name"
    private: "no"   #you can use false instead of no
  - name: "user password"
    prompt: "enter your password"
    private: "yes" #her instead of yes you can use true also

  tasks:
  - name: promting
    ansible.builtin.debug:
      msg: "print your user name: {{ username }}, print your password: {{ password }}"