- name: variables preference
  hosts: local
  connection: local
  # vars:
  #   NAME: "ansible from PLAY"
  # vars_files:
  #   # course.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: "enter your NAME"
  #   private: no
  tasks:
  - name: print NAME
    # vars:
    #   NAME: "Ansible from TASK"
    ansible.builtin.debug:
      msg: "Hi {{ NAME }}"
    
    # 1. ARGS
    # 2. TASK
    # 3. FILE
    # 4. PROMPT
    # 5. PLAY
    # 6. INVRNTORY
