- name: check the number less then 10 or not
  hosts: local
  connection: local
  vars:
    NUMBER OF SESSIONS: 7
  tasks:
  - name: is ansible more then 5 sessions
    ansible.builtin.debug:
      msg: "Yes, More the 5. sessions"
    when: NUMBER OF SESSIONS > 5