- name: printing gathering ansible facts
  hosts: local
  connection: local
  tasks:
  - name: ansible facts
    ansible.builtin.debug:
      msg: "Ansible facts {{ ansible_facts | ansible.builtin.to_nice_json }}"